// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	listInstances: () => typedError<Instance[], string>(__TAURI_INVOKE("list_instances")),
	createInstance: (req: CreateInstanceReq) => typedError<Instance, string>(__TAURI_INVOKE("create_instance", { req })),
	getInstance: (slug: string) => typedError<InstanceDetail, string>(__TAURI_INVOKE("get_instance", { slug })),
	deleteInstance: (slug: string) => typedError<null, string>(__TAURI_INVOKE("delete_instance", { slug })),
	getSettings: () => typedError<Settings, string>(__TAURI_INVOKE("get_settings")),
	saveSettings: (settings: Settings) => typedError<Settings, string>(__TAURI_INVOKE("save_settings", { settings })),
	appPaths: () => typedError<AppPaths, string>(__TAURI_INVOKE("app_paths")),
	listMinecraftVersions: () => typedError<McVersion[], string>(__TAURI_INVOKE("list_minecraft_versions")),
	getLoaders: (minecraft: string) => typedError<LoaderOption[], string>(__TAURI_INVOKE("get_loaders", { minecraft })),
	/**
	 *  Execute a [`DownloadPlan`] concurrently, emitting per-chunk progress on
	 *  the `download://progress` Tauri event channel.
	 * 
	 *  # Parameters
	 *  - `plan` — the list of files to download.
	 *  - `concurrency` — maximum simultaneous downloads (clamped to 1..=32).
	 *    Pass `null` / omit from TS to use the default (8).
	 */
	executeDownloadPlan: (plan: DownloadPlan, concurrency: number | null) => typedError<PlanResult, string>(__TAURI_INVOKE("execute_download_plan", { plan, concurrency })),
	/**
	 *  Resolve a vanilla Minecraft version into a `DownloadPlan` + `LaunchMeta`.
	 * 
	 *  Fetches + caches the per-version manifest (via `piston-meta`) and asset
	 *  index; assembles every file that must be present before launch (client jar,
	 *  libraries, natives, asset objects, asset index, logging config) into a
	 *  single `DownloadPlan`, and computes `LaunchMeta` for slice D.
	 */
	resolveVanilla: (versionId: string) => typedError<ResolveResult, string>(__TAURI_INVOKE("resolve_vanilla", { versionId })),
	/**
	 *  Detect or provision a JRE matching `major`.
	 * 
	 *  Probes system installs + the launcher cache first; downloads and extracts
	 *  Temurin from Adoptium only on a cache miss.
	 */
	ensureJava: (major: number) => typedError<JavaInstallation, string>(__TAURI_INVOKE("ensure_java", { major })),
	/**
	 *  Launch a vanilla Minecraft instance.
	 * 
	 *  Orchestrates: load instance → resolve → download → ensure Java →
	 *  extract natives → build argv → spawn JVM.
	 * 
	 *  Returns promptly; the child runs under a background `tokio::spawn` task that
	 *  streams stdout+stderr as `launch://log` events and records playtime on exit.
	 * 
	 *  The registry is managed as `Arc<RunningRegistry>` so the monitor task (which
	 *  runs under `tokio::spawn` and outlives this command's stack frame) can hold a
	 *  clone of the Arc and still access the shared map.
	 */
	launchInstance: (slug: string) => typedError<null, string>(__TAURI_INVOKE("launch_instance", { slug })),
	/**
	 *  Stop (kill) a running Minecraft instance.
	 * 
	 *  Fires the kill signal to the child process. The monitor task will then
	 *  record playtime and deregister the instance after the child actually exits.
	 * 
	 *  Returns `Ok` if the signal was sent, `Err` if the instance is not running.
	 */
	killInstance: (slug: string) => typedError<null, string>(__TAURI_INVOKE("kill_instance", { slug })),
	/**
	 *  Enumerate the currently non-terminal (preparing / running) instances.
	 * 
	 *  Lets any page hydrate the running-indicator state regardless of when it
	 *  mounted. Terminal entries (exited / killed / failed) are excluded.
	 */
	listRunning: () => __TAURI_INVOKE<RunInfoPayload[]>("list_running"),
	/**
	 *  Read a single instance's run state (any status, incl. terminal). `None` if the
	 *  slug is not tracked — lets `InstanceDetail` recover status + a missed exit code.
	 */
	getRunState: (slug: string) => __TAURI_INVOKE<{
	slug: string,
	/**  Lowercase status tag. */
	status: string,
	exitCode: number | null,
	/**  Milliseconds since the launch began. */
	elapsedMs: number,
} | null>("get_run_state", { slug }),
	/**
	 *  Replay an instance's buffered log lines (works after exit; entry is retained).
	 *  `None` if the slug is not tracked.
	 */
	getRunLogs: (slug: string) => __TAURI_INVOKE<RunLogPayload[] | null>("get_run_logs", { slug }),
	/**
	 *  Read the current Download-Manager task snapshot. Survives navigation —
	 *  any page can hydrate from this regardless of when it mounted.
	 */
	listTasks: () => typedError<Task_Serialize[], string>(__TAURI_INVOKE("list_tasks")),
	/**
	 *  Cancel a task by id. Trips the task's cancel token (a running download stops
	 *  acquiring new permits) and short-circuits a still-queued task to `Cancelled`.
	 *  Idempotent; a no-op for unknown or already-terminal ids.
	 */
	cancelTask: (id: number) => typedError<null, string>(__TAURI_INVOKE("cancel_task", { id })),
	/**
	 *  Start the Microsoft device-code login flow.
	 * 
	 *  Emits an `auth://device-code` event with `user_code` + `verification_uri`
	 *  before the first poll, then polls the MS token endpoint until resolved,
	 *  expired, or cancelled. On success, runs the Xbox chain, persists the
	 *  account (with the MS refresh token in the keyring), and returns the
	 *  `AccountMeta`.
	 * 
	 *  Pattern mirrors `launch_instance`: long-lived async command that emits
	 *  progress events via the Tauri event channel.
	 */
	beginLogin: () => typedError<AccountMeta_Serialize, AuthCommandError>(__TAURI_INVOKE("begin_login")),
	/**
	 *  Cancel an in-flight `begin_login` without panic or deadlock.
	 * 
	 *  If no login is in progress, this is a no-op.
	 */
	cancelLogin: () => __TAURI_INVOKE<void>("cancel_login"),
	/**  Get the current account metadata, or `None` if not logged in. */
	getAccount: () => typedError<{
	/**  Minecraft profile UUID (from `mc/profile`). */
	id: string,
	/**  Minecraft username. */
	username: string,
	/**  Xbox user ID. */
	xuid: string,
	/**
	 *  Unix timestamp (seconds) at which the MC token expires; `None` if unknown.
	 *  Alias keeps account.json files written before the camelCase rename loadable.
	 */
	mcTokenExpires: number | null,
} | null, AuthCommandError>(__TAURI_INVOKE("get_account")),
	/**  Log out: clear `account.json` and the keyring entry. */
	logout: () => typedError<null, AuthCommandError>(__TAURI_INVOKE("logout")),
	/**
	 *  Search mods across a single provider.
	 * 
	 *  `provider` must be `"modrinth"`, `"curseforge"`, `"ftb"`, or `"atlauncher"` (case-sensitive).
	 *  Unknown provider strings return a typed `unknown_provider` error rather than panicking.
	 *  The CF key is resolved from `MODLOADER_CF_API_KEY` env or `settings.curseforge_api_key`.
	 *  `project_type` selects the content class: `"mod"` (default) or `"modpack"`.
	 * 
	 *  `loaders` is an optional multi-loader filter (e.g. `["fabric","forge"]`).
	 *  `categories` carries per-provider category values already resolved by the
	 *  frontend (Modrinth: slug strings; CurseForge: numeric id strings).
	 *  Both default to empty (= no filter) when `None`.
	 */
	searchMods: (provider: string, query: string, mcVersion: string | null, loader: string | null, loaders: string[] | null, categories: string[] | null, offset: number, limit: number, projectType: 
/**  Standard mods (default). */
"mod" | 
/**  Modpacks. */
"modpack" | null) => typedError<SearchResult, ProviderCommandError>(__TAURI_INVOKE("search_mods", { provider, query, mcVersion, loader, loaders, categories, offset, limit, projectType })),
	/**
	 *  Fetch versions of a mod project compatible with the supplied MC version + loader.
	 * 
	 *  `provider` must be `"modrinth"` or `"curseforge"`.
	 */
	getModVersions: (provider: string, projectId: string, mcVersion: string | null, loader: string | null) => typedError<ProjectVersion[], ProviderCommandError>(__TAURI_INVOKE("get_mod_versions", { provider, projectId, mcVersion, loader })),
	/**
	 *  Fetch rich project info (title, long description, icon) for the Info tab.
	 * 
	 *  `provider` must be `"modrinth"` or `"curseforge"` (case-sensitive).
	 *  Modrinth returns Markdown (`body_is_html: false`); CurseForge returns HTML
	 *  (`body_is_html: true`). The CF key is resolved exactly like `search_mods`.
	 */
	getPackInfo: (provider: string, projectId: string) => typedError<PackInfo, ProviderCommandError>(__TAURI_INVOKE("get_pack_info", { provider, projectId })),
	/**
	 *  Back-fill metadata (`name`, `icon_url`, `summary`) for modpack-imported mods that
	 *  were added without display metadata (only search-added mods capture it at add-time).
	 * 
	 *  ## Frugality contract
	 *  - If all mods already have `name` set → returns `Ok(0)` with **zero** network calls.
	 *  - Otherwise issues **exactly one** batched call per provider with missing entries.
	 *  - Persists enriched metadata to the manifest so subsequent calls skip already-filled entries.
	 * 
	 *  ## Returns
	 *  The count of `ModEntry`s that were actually enriched.
	 */
	enrichInstanceMods: (slug: string) => typedError<number, string>(__TAURI_INVOKE("enrich_instance_mods", { slug })),
	/**
	 *  Install a mod (and its required transitive dependencies) into an instance.
	 * 
	 *  # Flow
	 *  1. Construct the provider + HTTP client (mirrors `search_mods` / `get_mod_versions`).
	 *  2. Fetch the requested version via `get_versions` filtered to the exact `version_id`.
	 *  3. Load the instance manifest; derive `already_installed` from `instance.mods`.
	 *  4. Run `resolve_install` (BFS dependency walk).
	 *  5. Build a `DownloadPlan` from `plan.downloads`; execute with `NoOpSink`.
	 *  6. For each successful download, build a `ModEntry` and merge into the manifest.
	 *  7. Save the manifest; return `AddModResult`.
	 * 
	 *  Per-item download failures are captured in `AddModResult.failed`; they do NOT
	 *  abort the whole operation (remaining items still execute).
	 *  Enqueue an add-mod task and return its task id synchronously.
	 * 
	 *  The `ensure_not_locked` guard runs here (synchronously, before enqueue) so a
	 *  locked instance errors without touching the queue. All download work runs
	 *  inside [`ModAddJob`].
	 */
	addMod: (provider: string, projectId: string, versionId: string, slug: string, mcVersion: string, loader: string, meta: ModMetadata) => typedError<number, string>(__TAURI_INVOKE("add_mod", { provider, projectId, versionId, slug, mcVersion, loader, meta })),
	/**
	 *  Enable or disable an installed mod by renaming its file and flipping the
	 *  `enabled` flag in the manifest.
	 * 
	 *  `file_name` is the base `.jar` name (no `.disabled` suffix). Both `slug`
	 *  and `file_name` are validated for path traversal before any FS access.
	 *  Blocked when the instance is pack-locked.
	 */
	setModEnabled: (slug: string, fileName: string, enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_mod_enabled", { slug, fileName, enabled })),
	/**
	 *  Delete a mod's on-disk file (enabled or disabled form) and drop its
	 *  manifest entry. Missing file is not an error — system converges to "gone".
	 * 
	 *  `file_name` is the base `.jar` name (no `.disabled` suffix). Both `slug`
	 *  and `file_name` are validated for path traversal before any FS access.
	 *  Blocked when the instance is pack-locked.
	 */
	removeMod: (slug: string, fileName: string) => typedError<null, string>(__TAURI_INVOKE("remove_mod", { slug, fileName })),
	/**
	 *  Enqueue an update-mod task and return its task id synchronously.
	 * 
	 *  The `ensure_not_locked` guard runs here (synchronously, before enqueue) so a
	 *  locked instance errors without touching the queue. The entry-existence check
	 *  also runs here so a bad project_id errors immediately. All download work runs
	 *  inside [`ModUpdateJob`].
	 */
	updateMod: (slug: string, projectId: string) => typedError<number, string>(__TAURI_INVOKE("update_mod", { slug, projectId })),
	/**
	 *  Set or clear the pack-lock flag on an instance.
	 * 
	 *  When locked, mod-mutation commands (`add_mod`, `set_mod_enabled`,
	 *  `remove_mod`, `update_mod`) will return an error. `update_modpack` is
	 *  deliberately left unguarded — updating the pack is how you change it.
	 */
	setPackLock: (slug: string, locked: boolean) => typedError<null, string>(__TAURI_INVOKE("set_pack_lock", { slug, locked })),
	/**
	 *  Set an instance's custom icon: copy the picked image into the instance dir
	 *  and record the relative filename on the manifest. Sync, instant FS op.
	 */
	setInstanceIcon: (slug: string, srcPath: string) => typedError<null, string>(__TAURI_INVOKE("set_instance_icon", { slug, srcPath })),
	/**  Clear an instance's custom icon (delete the file, reset `icon` to `None`). */
	clearInstanceIcon: (slug: string) => typedError<null, string>(__TAURI_INVOKE("clear_instance_icon", { slug })),
	/**
	 *  Persist the per-instance "don't warn me again" choice for the pre-launch
	 *  missing-mods dialog (CF manual-download UX). Sync, instant local op.
	 */
	setPendingLaunchWarningSuppressed: (slug: string, suppressed: boolean) => typedError<null, string>(__TAURI_INVOKE("set_pending_launch_warning_suppressed", { slug, suppressed })),
	/**
	 *  Rescan an instance's `mods/` for dropped manual downloads (Re-scan button /
	 *  fallback). Sync — instant local op, off the task queue. Returns the remaining
	 *  pending list.
	 */
	rescanPendingManual: (slug: string) => typedError<PendingManual[], string>(__TAURI_INVOKE("rescan_pending_manual", { slug })),
	/**
	 *  Manual fallback: copy a user-picked / dropped `.jar` into the instance's
	 *  `mods/` dir under its own file name, then reconcile. Resolves a pending entry
	 *  when the chosen file is named as the entry expects. Returns the remaining
	 *  pending list. Sync.
	 */
	importManualFile: (slug: string, srcPath: string) => typedError<PendingManual[], string>(__TAURI_INVOKE("import_manual_file", { slug, srcPath })),
	/**
	 *  Start a lazy watch on an instance's `mods/` dir (called from the detail page
	 *  when it mounts with pending files). Idempotent; replaces any prior watch.
	 */
	startPendingWatch: (slug: string) => typedError<null, string>(__TAURI_INVOKE("start_pending_watch", { slug })),
	/**
	 *  Stop the lazy `mods/` watch for an instance (detail page unmount / list
	 *  emptied). No-op if a different instance (or none) is being watched.
	 */
	stopPendingWatch: (slug: string) => typedError<null, string>(__TAURI_INVOKE("stop_pending_watch", { slug })),
	/**
	 *  Persist a `JavaCfg` override to an instance's manifest.
	 * 
	 *  When `cfg.use_pack_settings` is `true` the launcher uses this instance's own
	 *  Java/memory settings at launch; when `false` it falls back to the global
	 *  default from `Settings`. Resolution is handled by `resolve_effective_java`
	 *  (WS-A) — this command only persists the user's choice.
	 */
	setInstanceJava: (slug: string, java: JavaCfg) => typedError<null, string>(__TAURI_INVOKE("set_instance_java", { slug, java })),
	/**
	 *  Probe a Java binary by running `<path> -version` and parsing its stderr.
	 * 
	 *  Returns a [`JavaProbe`] with the major version and full version string on
	 *  success, or a human-readable `Err` when the binary cannot be spawned or its
	 *  output doesn't contain a recognisable `java version "…"` line.
	 */
	validateJavaPath: (path: string) => typedError<JavaProbe, string>(__TAURI_INVOKE("validate_java_path", { path })),
	/**
	 *  Enqueue an `.mrpack` import task and return its id synchronously.
	 * 
	 *  The task runs Plan → Download (staged) → Apply (promote + overrides + manifest).
	 *  The terminal `task://update` event carries the [`MrpackImportResult`] JSON.
	 */
	importMrpack: (mrpackPath: string, nameOverride: string | null) => typedError<number, string>(__TAURI_INVOKE("import_mrpack", { mrpackPath, nameOverride })),
	/**  Enqueue a CurseForge `.zip` import task and return its id synchronously. */
	importCurseforgeZip: (cfZipPath: string, nameOverride: string | null) => typedError<number, string>(__TAURI_INVOKE("import_curseforge_zip", { cfZipPath, nameOverride })),
	/**
	 *  Install a modpack from a Browse `ProjectSummary` in one click.
	 * 
	 *  Returns the enqueued task id. The terminal `task://update` event carries the
	 *  [`ModpackInstallResult`] JSON (Mrpack or Curseforge variant).
	 * 
	 *  Special case: if the resolved pack file has `url: None` (CF distribution-
	 *  disabled), the command returns `Err("MANUAL:<json>")` immediately — no task
	 *  is created. The JSON payload encodes `{ "pageUrl": "...", "fileName": "..." }`
	 *  so CP-7 can detect and route the manual case without a task. This preserves
	 *  the invariant that `Ok(u64)` always means "a task was enqueued."
	 */
	installModpack: (provider: string, projectId: string, pageUrl: string | null, versionId: string | null) => typedError<number, string>(__TAURI_INVOKE("install_modpack", { provider, projectId, pageUrl, versionId })),
	/**
	 *  Update an existing modpack instance. Resolves + downloads the archive
	 *  synchronously, then enqueues the job and returns the task id.
	 * 
	 *  The network resolution + archive download happen in the command body
	 *  (before enqueue) so that errors surface immediately. The heavy FS work
	 *  (plan execution, promote, overrides) runs in the task.
	 */
	updateModpack: (slug: string, versionId: string | null) => typedError<number, string>(__TAURI_INVOKE("update_modpack", { slug, versionId })),
	/**
	 *  Check whether a managed instance has an update available, throttled to once per 24h.
	 * 
	 *  Behaviour (spec PB-B3):
	 *  - No `source` on instance → `{ false, None, false }` (not a managed pack).
	 *  - `needs_update_check` returns false (within 24h) → return cached result, `checked: false`.
	 *  - Otherwise: fetch `get_pack_summary` (name/icon/author) + `get_versions` (newest [0]);
	 *    store results on `source`; `save_manifest`; return `{ update_available, latest_version, checked: true }`.
	 */
	refreshPackMeta: (slug: string) => typedError<PackMetaRefresh, string>(__TAURI_INVOKE("refresh_pack_meta", { slug })),
};

/** Events */
export const events = {
	authDeviceCode: makeEvent<DeviceCodePayload>("auth://device-code"),
	downloadProgress: makeEvent<ProgressPayload>("download://progress"),
	installLog: makeEvent<InstallLogPayload>("install://log"),
	launchExit: makeEvent<LaunchExitPayload>("launch://exit"),
	launchLog: makeEvent<LaunchLogPayload>("launch://log"),
	manualResolved: makeEvent<ManualResolvedPayload>("manual://resolved"),
	runUpdate: makeEvent<RunUpdatePayload>("run://update"),
	taskProgress: makeEvent<TaskProgressPayload>("task://progress"),
	taskUpdate: makeEvent<TaskUpdatePayload_Deserialize>("task://update"),
};

/* Types */
/**
 *  Non-secret account metadata written to `account.json`.
 * 
 *  The refresh token and MC access token are NOT stored here: the refresh token
 *  lives in the OS keyring (via [`KeyringBackend`]); the MC access token is
 *  re-derived at launch time.
 */
export type AccountMeta = AccountMeta_Serialize | AccountMeta_Deserialize;

/**
 *  Non-secret account metadata written to `account.json`.
 * 
 *  The refresh token and MC access token are NOT stored here: the refresh token
 *  lives in the OS keyring (via [`KeyringBackend`]); the MC access token is
 *  re-derived at launch time.
 */
export type AccountMeta_Deserialize = {
	/**  Minecraft profile UUID (from `mc/profile`). */
	id: string,
	/**  Minecraft username. */
	username: string,
	/**  Xbox user ID. */
	xuid: string,
} & {
	/**
	 *  Unix timestamp (seconds) at which the MC token expires; `None` if unknown.
	 *  Alias keeps account.json files written before the camelCase rename loadable.
	 */
	mcTokenExpires: number | null,
} | {
	/**
	 *  Unix timestamp (seconds) at which the MC token expires; `None` if unknown.
	 *  Alias keeps account.json files written before the camelCase rename loadable.
	 */
	mc_token_expires: number | null,
};

/**
 *  Non-secret account metadata written to `account.json`.
 * 
 *  The refresh token and MC access token are NOT stored here: the refresh token
 *  lives in the OS keyring (via [`KeyringBackend`]); the MC access token is
 *  re-derived at launch time.
 */
export type AccountMeta_Serialize = {
	/**  Minecraft profile UUID (from `mc/profile`). */
	id: string,
	/**  Minecraft username. */
	username: string,
	/**  Xbox user ID. */
	xuid: string,
	/**
	 *  Unix timestamp (seconds) at which the MC token expires; `None` if unknown.
	 *  Alias keeps account.json files written before the camelCase rename loadable.
	 */
	mcTokenExpires: number | null,
};

/**  Structured result returned by the `add_mod` Tauri command. */
export type AddModResult = {
	/**  `ModEntry` records for every successfully downloaded mod. */
	added: ModEntry[],
	/**  Mods that could not be auto-downloaded (distribution disabled). */
	manual: ManualMod[],
	/**  Dependencies with no compatible version. */
	unresolved: UnresolvedDep[],
	/**  Optional dependencies surfaced to the user. */
	suggestions: Suggestion[],
	/**  Incompatible mods declared by the dependency graph. */
	warnings: IncompatibleWarning[],
	/**  Mods that had a URL but whose download failed at runtime. */
	failed: FailedMod[],
};

/**  Basic app metadata, surfaced to the UI as the Phase-0 IPC smoke test. */
export type AppInfo = {
	name: string,
	version: string,
	tauriVersion: string,
};

/**  Resolved on-disk locations, surfaced read-only on the Settings page. */
export type AppPaths = {
	dataDir: string,
	instancesDir: string,
};

/**
 *  Serializable command error wrapping [`AuthError`] (F-5).
 * 
 *  `AuthError::Http` contains `reqwest::Error` which is not `Serialize`.
 *  This wrapper converts every variant to a string at the command boundary so
 *  the frontend always receives a JSON-serializable `{"error": "..."}` on
 *  failure. The named variant is preserved in the `kind` field for typed
 *  handling in the UI.
 */
export type AuthCommandError = {
	kind: string,
	message: string,
};

/**  Result returned to the frontend after a successful CurseForge `.zip` import. */
export type CfImportResult = {
	/**  Slug of the newly-created instance. */
	slug: string,
	/**  Display name of the instance (from the pack manifest or `name_override`). */
	name: string,
	/**  Number of pack files that were downloaded successfully. */
	installed: number,
	/**  Number of pack files whose download failed. */
	failed: number,
	/**
	 *  Files the user must download manually (distribution-disabled, or
	 *  resolved without a usable hash).
	 */
	manual: CfManualFile[],
};

/**
 *  A CurseForge file the user must download manually (distribution-disabled,
 *  or lacking a usable hash to verify an automated download).
 */
export type CfManualFile = {
	/**  CurseForge project (mod) id. */
	projectId: number,
	/**  CurseForge file id (specific version of the mod). */
	fileId: number,
	/**  Filename as declared by the resolved file. */
	fileName: string,
	/**
	 *  Best-effort CurseForge page URL — slug-based exact-file page when available
	 *  (`resolve_and_build_cf_plan`), else the numeric `…/projects/{id}` redirect.
	 */
	pageUrl: string,
	/**
	 *  SHA-1 of the file if CF declared one; `None` → name/size match only when the
	 *  user later drops the jar in (auto-recovery, Pillar 3).
	 */
	expectedSha1?: string | null,
	/**  Declared file size in bytes, if known. */
	size?: number | null,
};

/**
 *  A single child item within a task (one downloadable file).
 * 
 *  `label` is the human-facing name shown as the "current child" — derived from
 *  the [`DownloadItem.dest`](crate::core::download::DownloadItem) basename.
 */
export type ChildItem = {
	label: string,
};

export type CreateInstanceReq = {
	name: string,
	minecraft: string,
	loader: Loader,
};

/**  A declared dependency of a `ProjectVersion`. */
export type Dependency = {
	/**  Provider-specific project id of the dependency, if known. */
	projectId: string | null,
	/**  Provider-specific version id of the dependency, if known. */
	versionId: string | null,
	/**  Dependency type: `"required"`, `"optional"`, `"incompatible"`, or `"embedded"`. */
	dependencyType: string,
};

/**  Payload for the `auth://device-code` event emitted by `begin_login`. */
export type DeviceCodePayload = {
	userCode: string,
	verificationUri: string,
};

/**  A single file to download. */
export type DownloadItem = {
	/**  Source URL. */
	url: string,
	/**  Absolute destination path on disk. */
	dest: string,
	/**  Expected hash; `None` disables verification (not recommended). */
	expectedHash: ExpectedHash | null,
	/**  Expected file size in bytes; `None` if unknown. */
	size: number | null,
};

/**  An ordered list of [`DownloadItem`]s to execute as a unit. */
export type DownloadPlan = {
	items: DownloadItem[],
};

/**
 *  The expected hash for a single download item.
 * 
 *  The engine supports SHA-1 (used by Mojang asset objects), SHA-512
 *  (used by Modrinth files), SHA-256 (used by Adoptium/Temurin JRE
 *  checksums), and MD5 (used by ATLauncher mod jars).
 *  CurseForge fingerprints are out of scope until Phase 5.
 */
export type ExpectedHash = 
/**  SHA-1 hex digest. */
{ type: "sha1"; value: string } | 
/**  SHA-256 hex digest. */
{ type: "sha256"; value: string } | 
/**  SHA-512 hex digest. */
{ type: "sha512"; value: string } | 
/**  MD5 hex digest (used by ATLauncher mod jars). */
{ type: "md5"; value: string };

/**  A single file download that failed during `add_mod`. */
export type FailedMod = {
	/**  The `file_name` of the `PlannedMod` that failed. */
	fileName: string,
	/**  Human-readable error description. */
	error: string,
};

/**  A jar actually present in `mc/mods/`, whether or not it's tracked in `mods[]`. */
export type FolderMod = {
	fileName: string,
	/**  File ends in `.disabled` (the common enable/disable convention). */
	disabled: boolean,
	sizeBytes: number,
	/**  Matches an entry in the manifest's `mods[]` (managed vs. hand-dropped). */
	managed: boolean,
};

/**  A declared-incompatible mod. */
export type IncompatibleWarning = {
	/**  Provider-specific project id of the incompatible mod. */
	projectId: string,
};

/**
 *  Payload emitted on the `install://log` Tauri event channel.
 * 
 *  Distinct from `launch://log` — installer output is log-shaped (one line at
 *  a time from the installer's stdout/stderr), not item-progress-shaped.
 */
export type InstallLogPayload = {
	/**  `"stdout"` or `"stderr"`. */
	stream: string,
	line: string,
};

export type Instance = {
	schema: number,
	id: string,
	name: string,
	slug: string,
	icon: string | null,
	minecraft: string,
	loader: Loader,
	java: JavaCfg,
	source: Source | null,
	/**
	 *  When `true`, mod-mutation commands (`add_mod`, `set_mod_enabled`,
	 *  `remove_mod`, `update_mod`) are blocked. Set by `set_pack_lock` (slice D4).
	 *  Old manifests missing this field deserialize as `false`.
	 */
	packLocked?: boolean,
	/**
	 *  CF files that must be downloaded manually (distribution disabled). Drives the
	 *  "incomplete pack" badge/panel and the pre-launch warning. Empty for old manifests
	 *  and packs with no manual files. See `docs/design/cf-manual-download-ux.md`.
	 */
	pendingManual?: PendingManual[],
	/**
	 *  Per-instance "don't warn me again" for the pre-launch missing-mods dialog.
	 *  Old manifests deserialize as `false`.
	 */
	suppressPendingLaunchWarning?: boolean,
	mods: ModEntry[],
	created: string,
	lastPlayed: string | null,
	totalPlaytimeSec: number,
};

/**  `get` result: the manifest plus the reconciled mods-folder listing. */
export type InstanceDetail = {
	instance: Instance,
	folderMods: FolderMod[],
};

/**  The outcome of a single item within an executed [`DownloadPlan`]. */
export type ItemOutcome = {
	/**  The URL of the item this outcome belongs to. */
	url: string,
	/**  Whether the item succeeded, was skipped (dedupe), or failed. */
	status: ItemStatus,
};

/**  Per-item execution status returned by [`execute_plan`]. */
export type ItemStatus = 
/**  Downloaded and verified successfully. */
{ kind: "ok" } | 
/**  Destination already existed with a matching hash; no network request made. */
{ kind: "skipped" } | 
/**  Download or verification failed. */
{ kind: "failed"; error: string };

export type JavaCfg = {
	major: number | null,
	argsOverride: string | null,
	/**  Max heap (`-Xmx`). Also used as the instance's global-default value at create time. */
	memoryMb: number,
	/**  Min heap (`-Xms`). `None` = omit `-Xms` entirely (§8 Q5). */
	minMemoryMb?: number | null,
	/**  Custom java binary path. `None` = auto-provision via `ensure_java(major)`. */
	pathOverride?: string | null,
	/**
	 *  When `true`, this instance's saved Java/RAM override is used; when `false`,
	 *  the global default from `Settings` is used. Old manifests load as `false`.
	 */
	usePackSettings?: boolean,
};

/**  A located JRE. */
export type JavaInstallation = {
	/**  Java major version (e.g. 8, 17, 21). */
	major: number,
	/**  Absolute path to the `java` / `java.exe` executable. */
	path: string,
	/**  How this installation was discovered. */
	source: JavaSource,
};

/**  Result of probing a Java binary by running `java -version`. */
export type JavaProbe = {
	/**  Major version number (e.g. 8, 17, 21). */
	major: number,
	/**  Full version string as emitted by `java -version` (e.g. `"21.0.1"`). */
	version: string,
};

/**  How a [`JavaInstallation`] was found. */
export type JavaSource = 
/**  Detected from system paths / environment variables. */
"detected" | 
/**  Previously downloaded by the launcher. */
"downloaded";

/**  Payload emitted on the `launch://exit` Tauri event channel. */
export type LaunchExitPayload = {
	instanceId: string,
	/**  Process exit code; `null` if the code could not be determined. */
	code: number | null,
};

/**
 *  Payload emitted on the `launch://log` Tauri event channel.
 * 
 *  Mirrors the `CapturingLaunchSink` line tuple with serde rename so the
 *  TypeScript side receives camelCase field names.
 */
export type LaunchLogPayload = {
	instanceId: string,
	/**  `"stdout"` or `"stderr"`. */
	stream: string,
	line: string,
};

/**
 *  Accumulated metadata that slice D (launch) needs to build the JVM argv.
 * 
 *  All `${...}` placeholders in `jvm_args` and `game_args` are left intact —
 *  substitution is slice D's responsibility.
 */
export type LaunchMeta = {
	versionId: string,
	/**
	 *  The version type from the Mojang manifest: `"release"`, `"snapshot"`, etc.
	 *  Substituted into `${version_type}` by the argv assembler.
	 */
	versionType: string,
	mainClass: string,
	/**
	 *  JVM argument templates (modern `arguments.jvm` entries, OS-filtered).
	 *  Empty for legacy manifests — slice D provides defaults.
	 */
	jvmArgs: string[],
	/**  Game argument templates (modern `arguments.game` or legacy split). */
	gameArgs: string[],
	assetIndexId: string,
	assetsLegacy: boolean,
	javaMajor: number,
	/**  Ordered list of dest paths (as strings) for classpath: all libs + client jar. */
	classpath: string[],
	/**  Dest paths of native jars — slice D extracts these before launch. */
	natives: string[],
	/**  Path to the logging config file, if present in the manifest. */
	loggingConfig: string | null,
};

export type Loader = {
	/**  "vanilla" | "fabric" | "quilt" | "forge" | "neoforge" */
	kind: string,
	version: string | null,
};

export type LoaderOption = {
	/**  "vanilla" | "forge" | "fabric" | "quilt" | "neoforge" */
	kind: string,
	/**  Loader build versions, newest first. Empty for vanilla. */
	versions: string[],
};

/**
 *  A resolved mod file whose URL is `None` (distribution disabled).
 * 
 *  The user must manually download the file from `page_url`.
 */
export type ManualMod = {
	/**  Which provider owns this mod. */
	provider: ProviderKind,
	/**  Provider-specific project identifier. */
	projectId: string,
	/**  Provider-specific version identifier. */
	versionId: string,
	/**  Filename as declared by the provider. */
	fileName: string,
	/**  Project page URL — open in browser so user can download manually. */
	pageUrl: string,
};

/**
 *  Payload emitted on `manual://resolved` when a pending manual download is
 *  detected in an instance's `mods/` dir and recorded.
 */
export type ManualResolvedPayload = {
	slug: string,
	fileName: string,
	/**  Number of pending manual files still unresolved after this one. */
	remaining: number,
};

export type McVersion = {
	id: string,
	releaseTime: string,
};

export type ModEntry = {
	provider: string,
	projectId: string,
	versionId: string,
	fileName: string,
	hashes: { [key in string]: string },
	enabled: boolean,
	side: string,
	/**
	 *  `true` when this entry was written by a pack importer (slice D provenance).
	 *  `false` (default) for user-added mods. Old manifests missing this field
	 *  deserialize as `false` — no schema bump required.
	 */
	fromPack?: boolean,
	/**
	 *  Display name captured at add-time from the search result (`ProjectSummary.name`).
	 *  `None` for dependency-added mods and old manifests (no re-fetch to display).
	 */
	name?: string | null,
	/**
	 *  Icon URL captured at add-time from the search result (`ProjectSummary.icon_url`).
	 *  `None` for dependency-added mods and old manifests.
	 */
	iconUrl?: string | null,
	/**
	 *  Short description captured at add-time from the search result (`ProjectSummary.description`).
	 *  `None` for dependency-added mods and old manifests.
	 */
	summary?: string | null,
};

/**
 *  Display metadata captured at add-time from the search `ProjectSummary`.
 * 
 *  Passed as a single struct to `add_mod` to stay within specta's 10-arg limit.
 *  The frontend passes the `ProjectSummary`'s `name`, `icon_url`, and `description`
 *  fields. All are `None` for callers that don't have this data (e.g. tests).
 */
export type ModMetadata = {
	name: string | null,
	iconUrl: string | null,
	summary: string | null,
};

/**
 *  Tagged result returned to the frontend by `install_modpack`.
 * 
 *  The `kind` field discriminates which branch occurred so the frontend can
 *  render the correct toast without re-deriving the provider.
 * 
 *  - `"mrpack"` — Modrinth pack installed successfully.
 *  - `"curseforge"` — CurseForge pack installed; may carry a `manual` list for
 *    distribution-disabled files.
 *  - `"manual"` — the pack's primary file has `url: None` (distribution
 *    disabled at the pack level); no instance was created. The frontend should
 *    open `page_url` in the browser.
 */
export type ModpackInstallResult = 
/**  Modrinth `.mrpack` installed successfully. */
{
	kind: "mrpack",
} & MrpackImportResult | 
/**  CurseForge `.zip` installed (manual list may be non-empty). */
{
	kind: "curseforge",
} & CfImportResult | 
/**  Pack file is not distributable; frontend must open `page_url`. */
{ kind: "manual"; 
/**  Provider project page URL (echoed from the `page_url` parameter). */
pageUrl: string; 
/**  Filename as returned by the provider (useful for display). */
fileName: string };

/**  Result returned to the frontend after a successful `.mrpack` import. */
export type MrpackImportResult = {
	/**  Slug of the newly-created instance. */
	slug: string,
	/**  Display name of the instance (from the pack manifest or `name_override`). */
	name: string,
	/**  Number of pack files that were downloaded successfully. */
	installed: number,
	/**  Number of pack files whose download failed. */
	failed: number,
	/**  Number of pack files skipped because they are client-unsupported. */
	skipped: number,
	/**  File paths of any downloads that failed (empty on full success). */
	failedFiles: string[],
};

/**
 *  Rich project info for the Info tab — title, long description, and icon.
 * 
 *  Returned by `ModProvider::get_project`. The `description` field carries the
 *  full body: Markdown for Modrinth (`body_is_html: false`) or HTML for
 *  CurseForge (`body_is_html: true`).
 */
export type PackInfo = {
	/**  Display name of the project. */
	title: string,
	/**  Full long description (Markdown or HTML depending on `body_is_html`). */
	description: string,
	/**  Icon URL, if available. */
	iconUrl: string | null,
	/**  `true` if `description` is HTML (CurseForge); `false` if Markdown (Modrinth). */
	bodyIsHtml: boolean,
};

/**
 *  Response DTO for `refresh_pack_meta`.
 * 
 *  `update_available` — whether a newer version exists (latest_version_id != file_id).
 *  `latest_version`  — human-readable version string of the newest available release.
 *  `checked`         — `true` when this call actually polled the network (24h throttle expired
 *                      or first call); `false` when the cached result was returned without I/O.
 */
export type PackMetaRefresh = {
	updateAvailable: boolean,
	latestVersion: string | null,
	checked: boolean,
};

/**
 *  Result returned to the frontend by `update_modpack`.
 * 
 *  One struct for both providers (mrpack and CurseForge). `manual` is empty for
 *  mrpack updates and carries distribution-disabled files for CF updates, reusing
 *  the `CfManualFile` shape from slice B.
 */
export type PackUpdateResult = {
	/**  Number of pack mods newly added (file_name absent from the old pack mods). */
	added: number,
	/**  Number of old pack mods removed (were `from_pack=true`, absent from new plan). */
	removed: number,
	/**  Number of user-added mods kept (from_pack=false, not overwritten by new plan). */
	kept: number,
	/**  Number of download failures (+ CF resolve failures for CF packs). */
	failed: number,
	/**  Files the user must download manually (CF only; empty for mrpack). */
	manual: CfManualFile[],
};

/**
 *  A CurseForge file whose distribution is disabled (`allowModDistribution: false`)
 *  or which lacks a verifiable hash — the user must download it manually. Persisted on
 *  the manifest so the "incomplete pack" state survives restarts (see
 *  `docs/design/cf-manual-download-ux.md`). Cleared by `reconcile_pending_manual` once
 *  the matching jar appears in `mods/`.
 */
export type PendingManual = {
	/**  CF mod (project) id, stringified to match `ModEntry` convention. */
	projectId: string,
	/**  CF file id. */
	fileId: string,
	/**  Exact filename the user must drop into `mods/`. */
	fileName: string,
	/**  Slug-based exact-file URL (or numeric fallback) to fetch the jar from. */
	pageUrl: string,
	/**  SHA-1 to verify the dropped file against; `None` → name/size match only. */
	expectedSha1?: string | null,
	/**  Declared size in bytes for the name-only acceptance fallback. */
	size?: number | null,
};

/**
 *  Aggregated result returned by [`execute_plan`].
 * 
 *  Every item in the plan is represented exactly once. A failed item does NOT
 *  abort the others — all items run to completion, and the caller inspects the
 *  outcomes to decide what to do next.
 */
export type PlanResult = {
	outcomes: ItemOutcome[],
};

/**
 *  Payload emitted on the `download://progress` Tauri event channel.
 * 
 *  Mirrors [`ProgressUpdate`] with serde rename so the TypeScript side
 *  receives camelCase field names.
 */
export type ProgressPayload = {
	/**  Source URL of the item currently downloading. */
	url: string,
	/**  Bytes received so far for this item. */
	bytesDone: number,
	/**  Total expected bytes for this item; `null` when `Content-Length` was absent. */
	bytesTotal: number | null,
};

/**
 *  Condensed summary of a mod project, suitable for search result cards.
 * 
 *  Maps from both Modrinth `/search` hits and CF `/v1/mods/search` data entries.
 */
export type ProjectSummary = {
	/**  Which backend provided this result. */
	provider: ProviderKind,
	/**  Provider-specific project identifier (Modrinth: base62 string; CF: numeric id as string). */
	id: string,
	/**  URL-friendly slug (e.g. `"sodium"`). */
	slug: string,
	/**  Display name (e.g. `"Sodium"`). */
	name: string,
	/**  Short human-readable description. */
	summary: string,
	/**  Total all-time download count. */
	downloads: number,
	/**  Icon URL, if any. */
	iconUrl: string | null,
	/**  Category tags (normalized to lowercase strings). */
	categories: string[],
	/**
	 *  Provider project page URL, if available.
	 * 
	 *  Modrinth: `https://modrinth.com/{project_type}/{slug}` (derived from the response hit's
	 *  `project_type` field, not the search selector).
	 *  CurseForge: `links.websiteUrl` from the search row verbatim; `None` when absent/null.
	 */
	pageUrl: string | null,
};

/**
 *  Which class of projects to search for.
 * 
 *  Maps to provider-specific selectors:
 *  - Modrinth: `project_type` facet (`"mod"` or `"modpack"`).
 *  - CurseForge: `classId` query param (`6` for mods, `4471` for modpacks).
 */
export type ProjectType = 
/**  Standard mods (default). */
"mod" | 
/**  Modpacks. */
"modpack";

/**  A specific release of a mod project. */
export type ProjectVersion = {
	/**  Which backend provided this version. */
	provider: ProviderKind,
	/**  Version identifier (Modrinth: base62 id; CF: numeric file id as string). */
	id: string,
	/**  Human-readable name (e.g. `"Sodium 0.5.11 for MC 1.21"`). */
	name: string,
	/**  Semantic-ish version string (e.g. `"mc1.21-0.5.11"`). */
	versionNumber: string,
	/**  Compatible Minecraft versions (e.g. `["1.21", "1.20.4"]`). */
	gameVersions: string[],
	/**  Compatible mod loaders (e.g. `["fabric", "quilt"]`). */
	loaders: string[],
	/**  Downloadable files for this version. */
	files: VersionFile[],
	/**  Dependencies declared by this version. */
	dependencies: Dependency[],
};

/**
 *  Serializable command error wrapping [`ProviderError`].
 * 
 *  Mirrors `AuthCommandError` above. Every variant maps to a camelCase `kind`
 *  string; `"key_missing"` lets the frontend show the "API key required" state.
 */
export type ProviderCommandError = {
	kind: string,
	message: string,
};

/**  Identifies which provider owns a result. */
export type ProviderKind = "modrinth" | "curseForge" | "ftb" | "atlauncher";

/**
 *  Pack-recommended Java/memory hint embedded in the instance source.
 *  All fields are optional so a partial recommendation is valid.
 *  Currently always `None` — providers don't expose it yet (design §5).
 */
export type RecommendedJava = {
	memoryMb: number | null,
	javaArgs: string | null,
};

/**  Returned by `resolve_vanilla`: the download plan + launch metadata. */
export type ResolveResult = {
	plan: DownloadPlan,
	launch: LaunchMeta,
};

/**
 *  Run-state read payload returned by `list_running` / `get_run_state`.
 * 
 *  Mirrors [`launch::RunInfo`] with serde camelCase for the TypeScript side.
 */
export type RunInfoPayload = {
	slug: string,
	/**  Lowercase status tag. */
	status: string,
	exitCode: number | null,
	/**  Milliseconds since the launch began. */
	elapsedMs: number,
};

/**
 *  One replayed log line returned by `get_run_logs`.
 * 
 *  Mirrors [`launch::LogLine`] with serde camelCase.
 */
export type RunLogPayload = {
	/**  `"stdout"` or `"stderr"`. */
	stream: string,
	line: string,
};

/**
 *  Payload emitted on the `run://update` Tauri event channel.
 * 
 *  Fired on each run-status transition (`preparing` → `running` → terminal).
 *  Mirrors [`launch::RunInfo`]'s queryable scalars so the frontend runs slice can
 *  patch its state without a follow-up `get_run_state` round-trip.
 */
export type RunUpdatePayload = {
	/**  Instance slug (registry key). */
	slug: string,
	/**  Lowercase status tag: `preparing` / `running` / `exited` / `killed` / `failed`. */
	status: string,
	/**  Process exit code on a terminal status; `null` otherwise / if unknown. */
	exitCode: number | null,
};

/**  Paginated search response. */
export type SearchResult = {
	/**  Matching project summaries for this page. */
	hits: ProjectSummary[],
	/**  Zero-based offset of the first result in the full result set. */
	offset: number,
	/**  Total number of results matching the query (across all pages). */
	total: number,
};

export type Settings = {
	schema?: number,
	/**  RAM applied to newly created instances (MB). */
	defaultMemoryMb?: number,
	/**  Extra JVM args applied to instances with no per-instance override. */
	defaultJavaArgs?: string,
	/**
	 *  CurseForge API key (`x-api-key`). Backend-only — never sent to the webview
	 *  except to display/edit here. `None` until the user sets one.
	 */
	curseforgeApiKey?: string | null,
	/**
	 *  When true, always use the offline identity at launch regardless of whether
	 *  an active account is set. Default: false (use real account when available).
	 *  Preserves existing offline behavior for users with no account configured.
	 */
	offlineMode?: boolean,
	/**
	 *  When true, the sidebar starts collapsed on first launch (before the user has
	 *  manually toggled it). The live collapsed state is persisted in localStorage
	 *  (`apex-ui`); this setting is the initial seed applied on first run only.
	 */
	sidebarStartCollapsed?: boolean,
	/**
	 *  When true, `ensure_java` is called at launch to auto-download a JRE if none
	 *  is detected. When false, only detection is attempted; if no JRE is found the
	 *  launch is aborted with a message directing the user to configure Java manually.
	 *  Default: true (preserves existing behavior).
	 */
	autoDownloadJava?: boolean,
	/**
	 *  When true, the instance console panel starts expanded. When false, it starts
	 *  collapsed and the user must click to reveal it. Default: false.
	 */
	showConsoleDefault?: boolean,
	/**
	 *  When true (default), the launcher window stays open after launching an
	 *  instance. When false, the window is minimized immediately after a successful
	 *  launch (not closed — closing would kill run monitoring).
	 */
	keepLauncherOpen?: boolean,
	/**
	 *  When true (default), the launcher window is maximized on startup. Replaces
	 *  the static `"maximized": true` in `tauri.conf.json` with a dynamic check.
	 */
	maximizeOnStart?: boolean,
};

export type Source = {
	provider: string,
	projectId: string,
	fileId: string,
	packVersion: string,
	/**  Pack-recommended Java/RAM hint. Always `None` today — plumbing only. */
	recommended?: RecommendedJava | null,
	/**
	 *  Provider project page URL, captured at install-time from the browse/install
	 *  flow. `None` for instances imported via file drop or old manifests.
	 *  Used by AM-F3 "Open project page" button.
	 */
	pageUrl?: string | null,
	/**  Pack icon URL, populated by `refresh_pack_meta`. `None` until first refresh. */
	iconUrl?: string | null,
	/**
	 *  Pack author (CF: first/joined author name; Modrinth: owner username).
	 *  Populated by `refresh_pack_meta`. `None` until first refresh.
	 */
	author?: string | null,
	/**  RFC3339 timestamp of the last successful update-check. `None` if never checked. */
	lastUpdateCheck?: string | null,
	/**  Newest available version number (human-readable display), from last check. */
	latestVersion?: string | null,
	/**  Newest available version id (for the update action), from last check. */
	latestVersionId?: string | null,
	/**  Short one-line description captured by `refresh_pack_meta`. `None` until first refresh. */
	summary?: string | null,
	/**  Category tags captured by `refresh_pack_meta`. Empty until first refresh. */
	categories?: string[],
};

/**  An optional dependency surfaced as a suggestion. */
export type Suggestion = {
	/**  Provider-specific project id. */
	projectId: string,
	/**  Version id, if it was specified on the dependency (may be `None`). */
	versionId: string | null,
};

/**  A snapshot of one task's full state. Cloned out of the snapshot for reads. */
export type Task = Task_Serialize | Task_Deserialize;

/**
 *  The kind of work a task performs. Serialized as a camelCase tag for the
 *  frontend. CP-4 adds `ModAdd` / `ModUpdate`; the `Synthetic` variant exists
 *  for tests + the no-real-ops contract from CP-2.
 */
export type TaskKind = 
/**  Test / placeholder work with no real side effects. */
"synthetic" | 
/**  A new modpack install (import_mrpack, import_curseforge_zip, install_modpack). */
"packInstall" | 
/**  An update to an already-installed modpack (update_modpack). */
"packUpdate" | 
/**  Installing a mod (and its required transitive deps) into an instance. */
"modAdd" | 
/**  Updating a single installed mod to its newest compatible version. */
"modUpdate";

/**
 *  Payload emitted on the `task://progress` Tauri event channel.
 * 
 *  Mirrors [`task_manager::TaskProgress`] with serde camelCase. Fires per child
 *  transition while a task downloads. The frontend mirror lands in CP-7.
 */
export type TaskProgressPayload = {
	taskId: number,
	/**  Label of the child currently in flight; `null` between children. */
	currentChild: string | null,
	done: number,
	total: number,
	/**  Bytes received so far for the current child (best-effort). */
	bytes: number,
};

/**
 *  Typed union of all terminal task results.
 * 
 *  Carried by `Task.result` (via specta type override) and surfaced in the
 *  generated `bindings.ts` so the frontend can read `task.result` as a typed
 *  union rather than `any`. The runtime field in `Task` remains
 *  `Option<serde_json::Value>` (see `task_manager.rs`) and `finish_done_with_result`
 *  continues to accept `serde_json::Value`; this enum drives the TS type only.
 * 
 *  Wire shapes of the 6 variants match what `serde_json::to_value(&result)` writes
 *  for each corresponding result struct — no format change.
 */
export type TaskResult = 
/**  Result of `import_mrpack` / `install_modpack` (mrpack branch). */
MrpackImportResult | 
/**  Result of `import_curseforge_zip` / `install_modpack` (CF branch). */
CfImportResult | 
/**  Result of `install_modpack` (typed tagged union with `kind` field). */
ModpackInstallResult | 
/**  Result of `update_modpack`. */
PackUpdateResult | 
/**  Result of `add_mod`. */
AddModResult | 
/**  Result of `update_mod`. */
UpdateModResult;

/**
 *  Lifecycle status of a task. Matches the design's state diagram.
 * 
 *  Non-terminal: `Queued`, `Planning`, `Downloading`, `Applying`.
 *  Terminal: `Done`, `Failed`, `Cancelled`.
 */
export type TaskStatus = 
/**  Enqueued, not yet picked up by the worker. */
{ kind: "queued" } | 
/**  Worker is building the child queue (fetch manifest / resolve deps). */
{ kind: "planning" } | 
/**  Worker is downloading child items. */
{ kind: "downloading" } | 
/**  All children downloaded; applying (overlay / promote). */
{ kind: "applying" } | 
/**  Completed successfully. */
{ kind: "done" } | 
/**  Failed; `message` carries the reason. */
{ kind: "failed"; message: string } | 
/**  Cancelled before completion (from `Queued` or any running status). */
{ kind: "cancelled" };

/**
 *  Payload emitted on the `task://update` Tauri event channel — one full task
 *  snapshot per lifecycle/status transition.
 * 
 *  Mirrors [`task_manager::Task`] with serde camelCase. The status tag and
 *  child-item shapes already serialize camelCase from the core types. The
 *  frontend mirror lands in CP-7.
 */
export type TaskUpdatePayload = TaskUpdatePayload_Serialize | TaskUpdatePayload_Deserialize;

/**
 *  Payload emitted on the `task://update` Tauri event channel — one full task
 *  snapshot per lifecycle/status transition.
 * 
 *  Mirrors [`task_manager::Task`] with serde camelCase. The status tag and
 *  child-item shapes already serialize camelCase from the core types. The
 *  frontend mirror lands in CP-7.
 */
export type TaskUpdatePayload_Deserialize = Task_Deserialize;

/**
 *  Payload emitted on the `task://update` Tauri event channel — one full task
 *  snapshot per lifecycle/status transition.
 * 
 *  Mirrors [`task_manager::Task`] with serde camelCase. The status tag and
 *  child-item shapes already serialize camelCase from the core types. The
 *  frontend mirror lands in CP-7.
 */
export type TaskUpdatePayload_Serialize = Task_Serialize;

/**  A snapshot of one task's full state. Cloned out of the snapshot for reads. */
export type Task_Deserialize = {
	/**  Unique, monotonic task id (assigned at enqueue). */
	id: number,
	/**  What kind of work this is. */
	kind: TaskKind,
	/**  Human-facing parent label (e.g. "Install ATM10"). */
	parentLabel: string,
	/**  Current lifecycle status. */
	status: TaskStatus,
	/**  Child items, populated during the `Planning` phase. */
	children: ChildItem[],
	/**
	 *  Label of the child currently being processed; `None` outside the
	 *  `Downloading` phase.
	 */
	currentChild: string | null,
	/**  Number of children completed so far. */
	done: number,
	/**  Total number of children (set once the plan is built). */
	total: number,
	/**
	 *  Terminal result payload set by [`TaskContext::finish_done_with_result`].
	 *  `None` until the task reaches `Done` via that method; stays `None` for
	 *  tasks that finish via `finish_done` (no result), `finish_failed`, or
	 *  `finish_cancelled`. Serialized as `null` when absent.
	 * 
	 *  Stored as `serde_json::Value` at runtime for flexibility; the specta type
	 *  override points at [`crate::TaskResult`] so the generated `bindings.ts`
	 *  carries the typed union instead of an opaque `any`.
	 */
	result: TaskResult | null,
};

/**  A snapshot of one task's full state. Cloned out of the snapshot for reads. */
export type Task_Serialize = {
	/**  Unique, monotonic task id (assigned at enqueue). */
	id: number,
	/**  What kind of work this is. */
	kind: TaskKind,
	/**  Human-facing parent label (e.g. "Install ATM10"). */
	parentLabel: string,
	/**  Current lifecycle status. */
	status: TaskStatus,
	/**  Child items, populated during the `Planning` phase. */
	children: ChildItem[],
	/**
	 *  Label of the child currently being processed; `None` outside the
	 *  `Downloading` phase.
	 */
	currentChild: string | null,
	/**  Number of children completed so far. */
	done: number,
	/**  Total number of children (set once the plan is built). */
	total: number,
	/**
	 *  Terminal result payload set by [`TaskContext::finish_done_with_result`].
	 *  `None` until the task reaches `Done` via that method; stays `None` for
	 *  tasks that finish via `finish_done` (no result), `finish_failed`, or
	 *  `finish_cancelled`. Serialized as `null` when absent.
	 * 
	 *  Stored as `serde_json::Value` at runtime for flexibility; the specta type
	 *  override points at [`crate::TaskResult`] so the generated `bindings.ts`
	 *  carries the typed union instead of an opaque `any`.
	 */
	result?: TaskResult | null,
};

/**  A dependency for which no compatible version could be found. */
export type UnresolvedDep = {
	/**  Provider-specific project id of the unresolvable dep. */
	projectId: string,
	/**  Human-readable reason (e.g. `"no compatible version found"`). */
	reason: string,
};

/**  Structured result returned by the `update_mod` Tauri command. */
export type UpdateModResult = {
	/**  One of `"updated"` | `"upToDate"` | `"manual"` | `"unresolved"` | `"failed"`. */
	status: string,
	/**  Updated `ModEntry` on `"updated"`; `None` otherwise. */
	entry: ModEntry | null,
	/**  Project page URL on `"manual"` (open in browser). */
	pageUrl: string | null,
	/**  Human-readable error description on `"failed"`. */
	error: string | null,
};

/**
 *  A single downloadable file within a `ProjectVersion`.
 * 
 *  `url` is `None` when the author has disabled distribution (CF `allowModDistribution: false`
 *  or `downloadUrl: null`). The UI must surface a manual-download prompt in that case.
 */
export type VersionFile = {
	/**  Direct download URL; `None` means distribution is disabled. */
	url: string | null,
	/**  Filename as declared by the provider. */
	fileName: string,
	/**  File size in bytes, if known. */
	size: number | null,
	/**  Verification hashes keyed by algorithm name (e.g. `"sha1"`, `"sha512"`). */
	hashes: { [key in string]: string },
	/**  Whether this is the primary/recommended file for the version. */
	primary: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

