// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	listInstances: () => typedError<Instance[], string>(__TAURI_INVOKE("list_instances")),
	createInstance: (req: CreateInstanceReq) => typedError<Instance, string>(__TAURI_INVOKE("create_instance", { req })),
	getInstance: (slug: string) => typedError<InstanceDetail, string>(__TAURI_INVOKE("get_instance", { slug })),
	deleteInstance: (slug: string) => typedError<null, string>(__TAURI_INVOKE("delete_instance", { slug })),
	getSettings: () => typedError<Settings, string>(__TAURI_INVOKE("get_settings")),
	saveSettings: (settings: Settings) => typedError<Settings, string>(__TAURI_INVOKE("save_settings", { settings })),
	appPaths: () => typedError<AppPaths, string>(__TAURI_INVOKE("app_paths")),
	listMinecraftVersions: () => typedError<McVersion[], string>(__TAURI_INVOKE("list_minecraft_versions")),
	getLoaders: (minecraft: string) => typedError<LoaderOption[], string>(__TAURI_INVOKE("get_loaders", { minecraft })),
	/**
	 *  Execute a [`DownloadPlan`] concurrently, emitting per-chunk progress on
	 *  the `download://progress` Tauri event channel.
	 * 
	 *  # Parameters
	 *  - `plan` — the list of files to download.
	 *  - `concurrency` — maximum simultaneous downloads (clamped to 1..=32).
	 *    Pass `null` / omit from TS to use the default (8).
	 */
	executeDownloadPlan: (plan: DownloadPlan, concurrency: number | null) => typedError<PlanResult, string>(__TAURI_INVOKE("execute_download_plan", { plan, concurrency })),
	/**
	 *  Resolve a vanilla Minecraft version into a `DownloadPlan` + `LaunchMeta`.
	 * 
	 *  Fetches + caches the per-version manifest (via `piston-meta`) and asset
	 *  index; assembles every file that must be present before launch (client jar,
	 *  libraries, natives, asset objects, asset index, logging config) into a
	 *  single `DownloadPlan`, and computes `LaunchMeta` for slice D.
	 */
	resolveVanilla: (versionId: string) => typedError<ResolveResult, string>(__TAURI_INVOKE("resolve_vanilla", { versionId })),
	/**
	 *  Detect or provision a JRE matching `major`.
	 * 
	 *  Probes system installs + the launcher cache first; downloads and extracts
	 *  Temurin from Adoptium only on a cache miss.
	 */
	ensureJava: (major: number) => typedError<JavaInstallation, string>(__TAURI_INVOKE("ensure_java", { major })),
	/**
	 *  Launch a vanilla Minecraft instance.
	 * 
	 *  Orchestrates: load instance → resolve → download → ensure Java →
	 *  extract natives → build argv → spawn JVM.
	 * 
	 *  Returns promptly; the child runs under a background `tokio::spawn` task that
	 *  streams stdout+stderr as `launch://log` events and records playtime on exit.
	 * 
	 *  The registry is managed as `Arc<RunningRegistry>` so the monitor task (which
	 *  runs under `tokio::spawn` and outlives this command's stack frame) can hold a
	 *  clone of the Arc and still access the shared map.
	 */
	launchInstance: (slug: string) => typedError<null, string>(__TAURI_INVOKE("launch_instance", { slug })),
	/**
	 *  Stop (kill) a running Minecraft instance.
	 * 
	 *  Fires the kill signal to the child process. The monitor task will then
	 *  record playtime and deregister the instance after the child actually exits.
	 * 
	 *  Returns `Ok` if the signal was sent, `Err` if the instance is not running.
	 */
	killInstance: (slug: string) => typedError<null, string>(__TAURI_INVOKE("kill_instance", { slug })),
	/**
	 *  Enumerate the currently non-terminal (preparing / running) instances.
	 * 
	 *  Lets any page hydrate the running-indicator state regardless of when it
	 *  mounted. Terminal entries (exited / killed / failed) are excluded.
	 */
	listRunning: () => __TAURI_INVOKE<RunInfoPayload[]>("list_running"),
	/**
	 *  Read a single instance's run state (any status, incl. terminal). `None` if the
	 *  slug is not tracked — lets `InstanceDetail` recover status + a missed exit code.
	 */
	getRunState: (slug: string) => __TAURI_INVOKE<{
	slug: string,
	/**  Lowercase status tag. */
	status: string,
	exitCode: number | null,
	/**  Milliseconds since the launch began. */
	elapsedMs: number,
} | null>("get_run_state", { slug }),
	/**
	 *  Replay an instance's buffered log lines (works after exit; entry is retained).
	 *  `None` if the slug is not tracked.
	 */
	getRunLogs: (slug: string) => __TAURI_INVOKE<RunLogPayload[] | null>("get_run_logs", { slug }),
	/**
	 *  Read the current Download-Manager task snapshot. Survives navigation —
	 *  any page can hydrate from this regardless of when it mounted.
	 */
	listTasks: () => typedError<Task_Serialize[], string>(__TAURI_INVOKE("list_tasks")),
	/**
	 *  Cancel a task by id. Trips the task's cancel token (a running download stops
	 *  acquiring new permits) and short-circuits a still-queued task to `Cancelled`.
	 *  Idempotent; a no-op for unknown or already-terminal ids.
	 */
	cancelTask: (id: number) => typedError<null, string>(__TAURI_INVOKE("cancel_task", { id })),
	/**
	 *  Start the Microsoft device-code login flow.
	 * 
	 *  Emits an `auth://device-code` event with `user_code` + `verification_uri`
	 *  before the first poll, then polls the MS token endpoint until resolved,
	 *  expired, or cancelled. On success, runs the Xbox chain, persists the
	 *  account (with the MS refresh token in the keyring), and returns the
	 *  `AccountMeta`.
	 * 
	 *  Pattern mirrors `launch_instance`: long-lived async command that emits
	 *  progress events via the Tauri event channel.
	 */
	beginLogin: () => typedError<AccountMeta_Serialize, AuthCommandError>(__TAURI_INVOKE("begin_login")),
	/**
	 *  Cancel an in-flight `begin_login` without panic or deadlock.
	 * 
	 *  If no login is in progress, this is a no-op.
	 */
	cancelLogin: () => __TAURI_INVOKE<void>("cancel_login"),
	/**  Get the current account metadata, or `None` if not logged in. */
	getAccount: () => typedError<{
	/**  Minecraft profile UUID (from `mc/profile`). */
	id: string,
	/**  Minecraft username. */
	username: string,
	/**  Xbox user ID. */
	xuid: string,
	/**
	 *  Unix timestamp (seconds) at which the MC token expires; `None` if unknown.
	 *  Alias keeps account.json files written before the camelCase rename loadable.
	 */
	mcTokenExpires: number | null,
} | null, AuthCommandError>(__TAURI_INVOKE("get_account")),
	/**  Log out: clear `account.json` and the keyring entry. */
	logout: () => typedError<null, AuthCommandError>(__TAURI_INVOKE("logout")),
	/**
	 *  Search mods across a single provider.
	 * 
	 *  `provider` must be `"modrinth"` or `"curseforge"` (case-sensitive).
	 *  Unknown provider strings return a typed `unknown_provider` error rather than panicking.
	 *  The CF key is resolved from `MODLOADER_CF_API_KEY` env or `settings.curseforge_api_key`.
	 *  `project_type` selects the content class: `"mod"` (default) or `"modpack"`.
	 */
	searchMods: (provider: string, query: string, mcVersion: string | null, loader: string | null, offset: number, limit: number, projectType: 
/**  Standard mods (default). */
"mod" | 
/**  Modpacks. */
"modpack" | null) => typedError<SearchResult, ProviderCommandError>(__TAURI_INVOKE("search_mods", { provider, query, mcVersion, loader, offset, limit, projectType })),
	/**
	 *  Fetch versions of a mod project compatible with the supplied MC version + loader.
	 * 
	 *  `provider` must be `"modrinth"` or `"curseforge"`.
	 */
	getModVersions: (provider: string, projectId: string, mcVersion: string | null, loader: string | null) => typedError<ProjectVersion[], ProviderCommandError>(__TAURI_INVOKE("get_mod_versions", { provider, projectId, mcVersion, loader })),
	/**
	 *  Install a mod (and its required transitive dependencies) into an instance.
	 * 
	 *  # Flow
	 *  1. Construct the provider + HTTP client (mirrors `search_mods` / `get_mod_versions`).
	 *  2. Fetch the requested version via `get_versions` filtered to the exact `version_id`.
	 *  3. Load the instance manifest; derive `already_installed` from `instance.mods`.
	 *  4. Run `resolve_install` (BFS dependency walk).
	 *  5. Build a `DownloadPlan` from `plan.downloads`; execute with `NoOpSink`.
	 *  6. For each successful download, build a `ModEntry` and merge into the manifest.
	 *  7. Save the manifest; return `AddModResult`.
	 * 
	 *  Per-item download failures are captured in `AddModResult.failed`; they do NOT
	 *  abort the whole operation (remaining items still execute).
	 *  Enqueue an add-mod task and return its task id synchronously.
	 * 
	 *  The `ensure_not_locked` guard runs here (synchronously, before enqueue) so a
	 *  locked instance errors without touching the queue. All download work runs
	 *  inside [`ModAddJob`].
	 */
	addMod: (provider: string, projectId: string, versionId: string, slug: string, mcVersion: string, loader: string) => typedError<number, string>(__TAURI_INVOKE("add_mod", { provider, projectId, versionId, slug, mcVersion, loader })),
	/**
	 *  Enable or disable an installed mod by renaming its file and flipping the
	 *  `enabled` flag in the manifest.
	 * 
	 *  `file_name` is the base `.jar` name (no `.disabled` suffix). Both `slug`
	 *  and `file_name` are validated for path traversal before any FS access.
	 *  Blocked when the instance is pack-locked.
	 */
	setModEnabled: (slug: string, fileName: string, enabled: boolean) => typedError<null, string>(__TAURI_INVOKE("set_mod_enabled", { slug, fileName, enabled })),
	/**
	 *  Delete a mod's on-disk file (enabled or disabled form) and drop its
	 *  manifest entry. Missing file is not an error — system converges to "gone".
	 * 
	 *  `file_name` is the base `.jar` name (no `.disabled` suffix). Both `slug`
	 *  and `file_name` are validated for path traversal before any FS access.
	 *  Blocked when the instance is pack-locked.
	 */
	removeMod: (slug: string, fileName: string) => typedError<null, string>(__TAURI_INVOKE("remove_mod", { slug, fileName })),
	/**
	 *  Enqueue an update-mod task and return its task id synchronously.
	 * 
	 *  The `ensure_not_locked` guard runs here (synchronously, before enqueue) so a
	 *  locked instance errors without touching the queue. The entry-existence check
	 *  also runs here so a bad project_id errors immediately. All download work runs
	 *  inside [`ModUpdateJob`].
	 */
	updateMod: (slug: string, projectId: string) => typedError<number, string>(__TAURI_INVOKE("update_mod", { slug, projectId })),
	/**
	 *  Set or clear the pack-lock flag on an instance.
	 * 
	 *  When locked, mod-mutation commands (`add_mod`, `set_mod_enabled`,
	 *  `remove_mod`, `update_mod`) will return an error. `update_modpack` is
	 *  deliberately left unguarded — updating the pack is how you change it.
	 */
	setPackLock: (slug: string, locked: boolean) => typedError<null, string>(__TAURI_INVOKE("set_pack_lock", { slug, locked })),
	/**
	 *  Enqueue an `.mrpack` import task and return its id synchronously.
	 * 
	 *  The task runs Plan → Download (staged) → Apply (promote + overrides + manifest).
	 *  The terminal `task://update` event carries the [`MrpackImportResult`] JSON.
	 */
	importMrpack: (mrpackPath: string, nameOverride: string | null) => typedError<number, string>(__TAURI_INVOKE("import_mrpack", { mrpackPath, nameOverride })),
	/**  Enqueue a CurseForge `.zip` import task and return its id synchronously. */
	importCurseforgeZip: (cfZipPath: string, nameOverride: string | null) => typedError<number, string>(__TAURI_INVOKE("import_curseforge_zip", { cfZipPath, nameOverride })),
	/**
	 *  Install a modpack from a Browse `ProjectSummary` in one click.
	 * 
	 *  Returns the enqueued task id. The terminal `task://update` event carries the
	 *  [`ModpackInstallResult`] JSON (Mrpack or Curseforge variant).
	 * 
	 *  Special case: if the resolved pack file has `url: None` (CF distribution-
	 *  disabled), the command returns `Err("MANUAL:<json>")` immediately — no task
	 *  is created. The JSON payload encodes `{ "pageUrl": "...", "fileName": "..." }`
	 *  so CP-7 can detect and route the manual case without a task. This preserves
	 *  the invariant that `Ok(u64)` always means "a task was enqueued."
	 */
	installModpack: (provider: string, projectId: string, pageUrl: string | null, versionId: string | null) => typedError<number, string>(__TAURI_INVOKE("install_modpack", { provider, projectId, pageUrl, versionId })),
	/**
	 *  Update an existing modpack instance. Resolves + downloads the archive
	 *  synchronously, then enqueues the job and returns the task id.
	 * 
	 *  The network resolution + archive download happen in the command body
	 *  (before enqueue) so that errors surface immediately. The heavy FS work
	 *  (plan execution, promote, overrides) runs in the task.
	 */
	updateModpack: (slug: string, versionId: string | null) => typedError<number, string>(__TAURI_INVOKE("update_modpack", { slug, versionId })),
};

/* Types */
/**
 *  Non-secret account metadata written to `account.json`.
 * 
 *  The refresh token and MC access token are NOT stored here: the refresh token
 *  lives in the OS keyring (via [`KeyringBackend`]); the MC access token is
 *  re-derived at launch time.
 */
export type AccountMeta = AccountMeta_Serialize | AccountMeta_Deserialize;

/**
 *  Non-secret account metadata written to `account.json`.
 * 
 *  The refresh token and MC access token are NOT stored here: the refresh token
 *  lives in the OS keyring (via [`KeyringBackend`]); the MC access token is
 *  re-derived at launch time.
 */
export type AccountMeta_Deserialize = {
	/**  Minecraft profile UUID (from `mc/profile`). */
	id: string,
	/**  Minecraft username. */
	username: string,
	/**  Xbox user ID. */
	xuid: string,
} & {
	/**
	 *  Unix timestamp (seconds) at which the MC token expires; `None` if unknown.
	 *  Alias keeps account.json files written before the camelCase rename loadable.
	 */
	mcTokenExpires: number | null,
} | {
	/**
	 *  Unix timestamp (seconds) at which the MC token expires; `None` if unknown.
	 *  Alias keeps account.json files written before the camelCase rename loadable.
	 */
	mc_token_expires: number | null,
};

/**
 *  Non-secret account metadata written to `account.json`.
 * 
 *  The refresh token and MC access token are NOT stored here: the refresh token
 *  lives in the OS keyring (via [`KeyringBackend`]); the MC access token is
 *  re-derived at launch time.
 */
export type AccountMeta_Serialize = {
	/**  Minecraft profile UUID (from `mc/profile`). */
	id: string,
	/**  Minecraft username. */
	username: string,
	/**  Xbox user ID. */
	xuid: string,
	/**
	 *  Unix timestamp (seconds) at which the MC token expires; `None` if unknown.
	 *  Alias keeps account.json files written before the camelCase rename loadable.
	 */
	mcTokenExpires: number | null,
};

/**  Basic app metadata, surfaced to the UI as the Phase-0 IPC smoke test. */
export type AppInfo = {
	name: string,
	version: string,
	tauriVersion: string,
};

/**  Resolved on-disk locations, surfaced read-only on the Settings page. */
export type AppPaths = {
	dataDir: string,
	instancesDir: string,
};

/**
 *  Serializable command error wrapping [`AuthError`] (F-5).
 * 
 *  `AuthError::Http` contains `reqwest::Error` which is not `Serialize`.
 *  This wrapper converts every variant to a string at the command boundary so
 *  the frontend always receives a JSON-serializable `{"error": "..."}` on
 *  failure. The named variant is preserved in the `kind` field for typed
 *  handling in the UI.
 */
export type AuthCommandError = {
	kind: string,
	message: string,
};

/**
 *  A single child item within a task (one downloadable file).
 * 
 *  `label` is the human-facing name shown as the "current child" — derived from
 *  the [`DownloadItem.dest`](crate::core::download::DownloadItem) basename.
 */
export type ChildItem = {
	label: string,
};

export type CreateInstanceReq = {
	name: string,
	minecraft: string,
	loader: Loader,
};

/**  A declared dependency of a `ProjectVersion`. */
export type Dependency = {
	/**  Provider-specific project id of the dependency, if known. */
	projectId: string | null,
	/**  Provider-specific version id of the dependency, if known. */
	versionId: string | null,
	/**  Dependency type: `"required"`, `"optional"`, `"incompatible"`, or `"embedded"`. */
	dependencyType: string,
};

/**  A single file to download. */
export type DownloadItem = {
	/**  Source URL. */
	url: string,
	/**  Absolute destination path on disk. */
	dest: string,
	/**  Expected hash; `None` disables verification (not recommended). */
	expectedHash: ExpectedHash | null,
	/**  Expected file size in bytes; `None` if unknown. */
	size: number | null,
};

/**  An ordered list of [`DownloadItem`]s to execute as a unit. */
export type DownloadPlan = {
	items: DownloadItem[],
};

/**
 *  The expected hash for a single download item.
 * 
 *  The engine supports SHA-1 (used by Mojang asset objects), SHA-512
 *  (used by Modrinth files), and SHA-256 (used by Adoptium/Temurin JRE
 *  checksums). CurseForge fingerprints are out of scope until Phase 5.
 */
export type ExpectedHash = 
/**  SHA-1 hex digest. */
{ type: "sha1"; value: string } | 
/**  SHA-256 hex digest. */
{ type: "sha256"; value: string } | 
/**  SHA-512 hex digest. */
{ type: "sha512"; value: string };

/**  A jar actually present in `mc/mods/`, whether or not it's tracked in `mods[]`. */
export type FolderMod = {
	fileName: string,
	/**  File ends in `.disabled` (the common enable/disable convention). */
	disabled: boolean,
	sizeBytes: number,
	/**  Matches an entry in the manifest's `mods[]` (managed vs. hand-dropped). */
	managed: boolean,
};

export type Instance = {
	schema: number,
	id: string,
	name: string,
	slug: string,
	icon: string | null,
	minecraft: string,
	loader: Loader,
	java: JavaCfg,
	source: Source | null,
	/**
	 *  When `true`, mod-mutation commands (`add_mod`, `set_mod_enabled`,
	 *  `remove_mod`, `update_mod`) are blocked. Set by `set_pack_lock` (slice D4).
	 *  Old manifests missing this field deserialize as `false`.
	 */
	packLocked?: boolean,
	mods: ModEntry[],
	created: string,
	lastPlayed: string | null,
	totalPlaytimeSec: number,
};

/**  `get` result: the manifest plus the reconciled mods-folder listing. */
export type InstanceDetail = {
	instance: Instance,
	folderMods: FolderMod[],
};

/**  The outcome of a single item within an executed [`DownloadPlan`]. */
export type ItemOutcome = {
	/**  The URL of the item this outcome belongs to. */
	url: string,
	/**  Whether the item succeeded, was skipped (dedupe), or failed. */
	status: ItemStatus,
};

/**  Per-item execution status returned by [`execute_plan`]. */
export type ItemStatus = 
/**  Downloaded and verified successfully. */
{ kind: "ok" } | 
/**  Destination already existed with a matching hash; no network request made. */
{ kind: "skipped" } | 
/**  Download or verification failed. */
{ kind: "failed"; error: string };

export type JavaCfg = {
	major: number | null,
	argsOverride: string | null,
	memoryMb: number,
};

/**  A located JRE. */
export type JavaInstallation = {
	/**  Java major version (e.g. 8, 17, 21). */
	major: number,
	/**  Absolute path to the `java` / `java.exe` executable. */
	path: string,
	/**  How this installation was discovered. */
	source: JavaSource,
};

/**  How a [`JavaInstallation`] was found. */
export type JavaSource = 
/**  Detected from system paths / environment variables. */
"detected" | 
/**  Previously downloaded by the launcher. */
"downloaded";

/**
 *  Accumulated metadata that slice D (launch) needs to build the JVM argv.
 * 
 *  All `${...}` placeholders in `jvm_args` and `game_args` are left intact —
 *  substitution is slice D's responsibility.
 */
export type LaunchMeta = {
	versionId: string,
	/**
	 *  The version type from the Mojang manifest: `"release"`, `"snapshot"`, etc.
	 *  Substituted into `${version_type}` by the argv assembler.
	 */
	versionType: string,
	mainClass: string,
	/**
	 *  JVM argument templates (modern `arguments.jvm` entries, OS-filtered).
	 *  Empty for legacy manifests — slice D provides defaults.
	 */
	jvmArgs: string[],
	/**  Game argument templates (modern `arguments.game` or legacy split). */
	gameArgs: string[],
	assetIndexId: string,
	assetsLegacy: boolean,
	javaMajor: number,
	/**  Ordered list of dest paths (as strings) for classpath: all libs + client jar. */
	classpath: string[],
	/**  Dest paths of native jars — slice D extracts these before launch. */
	natives: string[],
	/**  Path to the logging config file, if present in the manifest. */
	loggingConfig: string | null,
};

export type Loader = {
	/**  "vanilla" | "fabric" | "quilt" | "forge" | "neoforge" */
	kind: string,
	version: string | null,
};

export type LoaderOption = {
	/**  "vanilla" | "forge" | "fabric" | "quilt" | "neoforge" */
	kind: string,
	/**  Loader build versions, newest first. Empty for vanilla. */
	versions: string[],
};

export type McVersion = {
	id: string,
	releaseTime: string,
};

export type ModEntry = {
	provider: string,
	projectId: string,
	versionId: string,
	fileName: string,
	hashes: { [key in string]: string },
	enabled: boolean,
	side: string,
	/**
	 *  `true` when this entry was written by a pack importer (slice D provenance).
	 *  `false` (default) for user-added mods. Old manifests missing this field
	 *  deserialize as `false` — no schema bump required.
	 */
	fromPack?: boolean,
};

/**
 *  Aggregated result returned by [`execute_plan`].
 * 
 *  Every item in the plan is represented exactly once. A failed item does NOT
 *  abort the others — all items run to completion, and the caller inspects the
 *  outcomes to decide what to do next.
 */
export type PlanResult = {
	outcomes: ItemOutcome[],
};

/**
 *  Condensed summary of a mod project, suitable for search result cards.
 * 
 *  Maps from both Modrinth `/search` hits and CF `/v1/mods/search` data entries.
 */
export type ProjectSummary = {
	/**  Which backend provided this result. */
	provider: ProviderKind,
	/**  Provider-specific project identifier (Modrinth: base62 string; CF: numeric id as string). */
	id: string,
	/**  URL-friendly slug (e.g. `"sodium"`). */
	slug: string,
	/**  Display name (e.g. `"Sodium"`). */
	name: string,
	/**  Short human-readable description. */
	summary: string,
	/**  Total all-time download count. */
	downloads: number,
	/**  Icon URL, if any. */
	iconUrl: string | null,
	/**  Category tags (normalized to lowercase strings). */
	categories: string[],
	/**
	 *  Provider project page URL, if available.
	 * 
	 *  Modrinth: `https://modrinth.com/{project_type}/{slug}` (derived from the response hit's
	 *  `project_type` field, not the search selector).
	 *  CurseForge: `links.websiteUrl` from the search row verbatim; `None` when absent/null.
	 */
	pageUrl: string | null,
};

/**
 *  Which class of projects to search for.
 * 
 *  Maps to provider-specific selectors:
 *  - Modrinth: `project_type` facet (`"mod"` or `"modpack"`).
 *  - CurseForge: `classId` query param (`6` for mods, `4471` for modpacks).
 */
export type ProjectType = 
/**  Standard mods (default). */
"mod" | 
/**  Modpacks. */
"modpack";

/**  A specific release of a mod project. */
export type ProjectVersion = {
	/**  Which backend provided this version. */
	provider: ProviderKind,
	/**  Version identifier (Modrinth: base62 id; CF: numeric file id as string). */
	id: string,
	/**  Human-readable name (e.g. `"Sodium 0.5.11 for MC 1.21"`). */
	name: string,
	/**  Semantic-ish version string (e.g. `"mc1.21-0.5.11"`). */
	versionNumber: string,
	/**  Compatible Minecraft versions (e.g. `["1.21", "1.20.4"]`). */
	gameVersions: string[],
	/**  Compatible mod loaders (e.g. `["fabric", "quilt"]`). */
	loaders: string[],
	/**  Downloadable files for this version. */
	files: VersionFile[],
	/**  Dependencies declared by this version. */
	dependencies: Dependency[],
};

/**
 *  Serializable command error wrapping [`ProviderError`].
 * 
 *  Mirrors `AuthCommandError` above. Every variant maps to a camelCase `kind`
 *  string; `"key_missing"` lets the frontend show the "API key required" state.
 */
export type ProviderCommandError = {
	kind: string,
	message: string,
};

/**  Identifies which provider owns a result. */
export type ProviderKind = "modrinth" | "curseForge";

/**  Returned by `resolve_vanilla`: the download plan + launch metadata. */
export type ResolveResult = {
	plan: DownloadPlan,
	launch: LaunchMeta,
};

/**
 *  Run-state read payload returned by `list_running` / `get_run_state`.
 * 
 *  Mirrors [`launch::RunInfo`] with serde camelCase for the TypeScript side.
 */
export type RunInfoPayload = {
	slug: string,
	/**  Lowercase status tag. */
	status: string,
	exitCode: number | null,
	/**  Milliseconds since the launch began. */
	elapsedMs: number,
};

/**
 *  One replayed log line returned by `get_run_logs`.
 * 
 *  Mirrors [`launch::LogLine`] with serde camelCase.
 */
export type RunLogPayload = {
	/**  `"stdout"` or `"stderr"`. */
	stream: string,
	line: string,
};

/**  Paginated search response. */
export type SearchResult = {
	/**  Matching project summaries for this page. */
	hits: ProjectSummary[],
	/**  Zero-based offset of the first result in the full result set. */
	offset: number,
	/**  Total number of results matching the query (across all pages). */
	total: number,
};

export type Settings = {
	schema?: number,
	/**  RAM applied to newly created instances (MB). */
	defaultMemoryMb?: number,
	/**  Extra JVM args applied to instances with no per-instance override. */
	defaultJavaArgs?: string,
	/**
	 *  CurseForge API key (`x-api-key`). Backend-only — never sent to the webview
	 *  except to display/edit here. `None` until the user sets one.
	 */
	curseforgeApiKey?: string | null,
	/**
	 *  When true, always use the offline identity at launch regardless of whether
	 *  an active account is set. Default: false (use real account when available).
	 *  Preserves existing offline behavior for users with no account configured.
	 */
	offlineMode?: boolean,
};

export type Source = {
	provider: string,
	projectId: string,
	fileId: string,
	packVersion: string,
};

/**  A snapshot of one task's full state. Cloned out of the snapshot for reads. */
export type Task = Task_Serialize | Task_Deserialize;

/**
 *  The kind of work a task performs. Serialized as a camelCase tag for the
 *  frontend. CP-4 adds `ModAdd` / `ModUpdate`; the `Synthetic` variant exists
 *  for tests + the no-real-ops contract from CP-2.
 */
export type TaskKind = 
/**  Test / placeholder work with no real side effects. */
"synthetic" | 
/**  A new modpack install (import_mrpack, import_curseforge_zip, install_modpack). */
"packInstall" | 
/**  An update to an already-installed modpack (update_modpack). */
"packUpdate" | 
/**  Installing a mod (and its required transitive deps) into an instance. */
"modAdd" | 
/**  Updating a single installed mod to its newest compatible version. */
"modUpdate";

/**
 *  Lifecycle status of a task. Matches the design's state diagram.
 * 
 *  Non-terminal: `Queued`, `Planning`, `Downloading`, `Applying`.
 *  Terminal: `Done`, `Failed`, `Cancelled`.
 */
export type TaskStatus = 
/**  Enqueued, not yet picked up by the worker. */
{ kind: "queued" } | 
/**  Worker is building the child queue (fetch manifest / resolve deps). */
{ kind: "planning" } | 
/**  Worker is downloading child items. */
{ kind: "downloading" } | 
/**  All children downloaded; applying (overlay / promote). */
{ kind: "applying" } | 
/**  Completed successfully. */
{ kind: "done" } | 
/**  Failed; `message` carries the reason. */
{ kind: "failed"; message: string } | 
/**  Cancelled before completion (from `Queued` or any running status). */
{ kind: "cancelled" };

/**  A snapshot of one task's full state. Cloned out of the snapshot for reads. */
export type Task_Deserialize = {
	/**  Unique, monotonic task id (assigned at enqueue). */
	id: number,
	/**  What kind of work this is. */
	kind: TaskKind,
	/**  Human-facing parent label (e.g. "Install ATM10"). */
	parentLabel: string,
	/**  Current lifecycle status. */
	status: TaskStatus,
	/**  Child items, populated during the `Planning` phase. */
	children: ChildItem[],
	/**
	 *  Label of the child currently being processed; `None` outside the
	 *  `Downloading` phase.
	 */
	currentChild: string | null,
	/**  Number of children completed so far. */
	done: number,
	/**  Total number of children (set once the plan is built). */
	total: number,
};

/**  A snapshot of one task's full state. Cloned out of the snapshot for reads. */
export type Task_Serialize = {
	/**  Unique, monotonic task id (assigned at enqueue). */
	id: number,
	/**  What kind of work this is. */
	kind: TaskKind,
	/**  Human-facing parent label (e.g. "Install ATM10"). */
	parentLabel: string,
	/**  Current lifecycle status. */
	status: TaskStatus,
	/**  Child items, populated during the `Planning` phase. */
	children: ChildItem[],
	/**
	 *  Label of the child currently being processed; `None` outside the
	 *  `Downloading` phase.
	 */
	currentChild: string | null,
	/**  Number of children completed so far. */
	done: number,
	/**  Total number of children (set once the plan is built). */
	total: number,
};

/**
 *  A single downloadable file within a `ProjectVersion`.
 * 
 *  `url` is `None` when the author has disabled distribution (CF `allowModDistribution: false`
 *  or `downloadUrl: null`). The UI must surface a manual-download prompt in that case.
 */
export type VersionFile = {
	/**  Direct download URL; `None` means distribution is disabled. */
	url: string | null,
	/**  Filename as declared by the provider. */
	fileName: string,
	/**  File size in bytes, if known. */
	size: number | null,
	/**  Verification hashes keyed by algorithm name (e.g. `"sha1"`, `"sha512"`). */
	hashes: { [key in string]: string },
	/**  Whether this is the primary/recommended file for the version. */
	primary: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

