//! Fabric / Quilt loader profile fetcher and parser.
//!
//! The loader profile is a Mojang launcher-profile JSON that describes:
//! - `mainClass` — overrides the vanilla entry point (KnotClient for Fabric/Quilt).
//! - `libraries` — additional JARs needed on the classpath (Maven coordinates + base URL).
//! - `arguments` — optional extra JVM/game args in the same modern format as the vanilla manifest.
//!
//! `fetch_profile` caches the response via `meta::cached_text` with a 6-hour TTL, matching the
//! TTL used by `loaders.rs` for the version list.

use std::path::Path;
use std::time::Duration;

use serde::Deserialize;
use tauri::AppHandle;

use crate::core::meta;
use crate::core::resolver::Arguments;

const TTL: Duration = Duration::from_secs(6 * 3600);

// ---------------------------------------------------------------------------
// Data types
// ---------------------------------------------------------------------------

/// A library entry in the loader profile. Each entry has a Maven coordinate
/// (`name`) and an optional base Maven repository URL (`url`).
///
/// `url` is `None` for processor-produced libraries in Forge `version.json` that
/// have no download URL — those are added to the classpath only, not downloaded.
/// Fabric/Quilt profiles always supply a `url`; the field deserialises as
/// `Some("...")` from a plain string value.
#[derive(Debug, Deserialize, PartialEq)]
pub struct LoaderLibrary {
    pub name: String,
    #[serde(default)]
    pub url: Option<String>,
}

/// Parsed representation of a Fabric / Quilt / Forge loader profile JSON.
///
/// Serde-tolerant: unknown fields are ignored, all optional blocks default to
/// their zero values so the struct parses even if the API ever omits a section.
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LoaderProfile {
    pub main_class: String,
    /// Identifies the vanilla base version that this profile extends.
    /// Present in Forge/NeoForge `version.json`; absent in Fabric/Quilt profiles.
    /// Load-only — no validation logic in this slice.
    #[serde(default)]
    pub inherits_from: Option<String>,
    #[serde(default)]
    pub libraries: Vec<LoaderLibrary>,
    #[serde(default)]
    pub arguments: Arguments,
}

// ---------------------------------------------------------------------------
// Forge / NeoForge version.json deserialization helpers
// ---------------------------------------------------------------------------

/// Artifact block inside a Forge library's `downloads` object.
/// Matches the vanilla `DownloadSpec` shape (url, sha1, size, path).
#[derive(Debug, Deserialize)]
struct ForgeArtifact {
    pub url: String,
}

/// `downloads` object inside a Forge library entry.
#[derive(Debug, Deserialize, Default)]
struct ForgeLibraryDownloads {
    pub artifact: Option<ForgeArtifact>,
}

/// A single library entry in a Forge/NeoForge `version.json`.
///
/// Forge uses a vanilla-style `downloads.artifact.url` layout rather than
/// the Fabric-style flat `url` field.
#[derive(Debug, Deserialize)]
struct ForgeLibrary {
    pub name: String,
    #[serde(default)]
    pub downloads: ForgeLibraryDownloads,
}

/// Minimal parse target for a Forge/NeoForge `version.json`.
///
/// Only the fields needed for launch are captured; processor-related fields
/// (`processors`, `data`) are ignored via `#[serde(deny_unknown_fields)]`
/// absence (default serde behaviour is to skip unknowns).
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct ForgeVersionJson {
    pub main_class: String,
    #[serde(default)]
    pub inherits_from: Option<String>,
    #[serde(default)]
    pub libraries: Vec<ForgeLibrary>,
    #[serde(default)]
    pub arguments: Arguments,
}

// ---------------------------------------------------------------------------
// Forge profile loader (disk, no HTTP)
// ---------------------------------------------------------------------------

/// Read and parse a Forge/NeoForge `version.json` from disk, returning a
/// [`LoaderProfile`] suitable for use with [`crate::core::resolver::merge_loader_profile`].
///
/// Each library's URL is extracted from `downloads.artifact.url` when present;
/// processor-produced libraries (no artifact) get `url: None` and will be added
/// to the classpath only (no download item generated by the merge step).
pub fn load_forge_profile(path: &Path) -> Result<LoaderProfile, String> {
    let raw = std::fs::read_to_string(path)
        .map_err(|e| format!("cannot read forge profile {}: {e}", path.display()))?;
    let forge: ForgeVersionJson = serde_json::from_str(&raw)
        .map_err(|e| format!("forge profile parse error at {}: {e}", path.display()))?;

    let libraries: Vec<LoaderLibrary> = forge
        .libraries
        .into_iter()
        .map(|lib| {
            let url = lib.downloads.artifact.map(|a| a.url);
            LoaderLibrary { name: lib.name, url }
        })
        .collect();

    Ok(LoaderProfile {
        main_class: forge.main_class,
        inherits_from: forge.inherits_from,
        libraries,
        arguments: forge.arguments,
    })
}

// ---------------------------------------------------------------------------
// URL builder (pure — unit-testable without network)
// ---------------------------------------------------------------------------

/// Build the profile JSON URL for the given loader kind, MC version, and loader version.
///
/// Returns `Err` for unknown loader kinds.
pub fn profile_url(kind: &str, mc: &str, loader: &str) -> Result<String, String> {
    match kind {
        "fabric" => Ok(format!(
            "https://meta.fabricmc.net/v2/versions/loader/{mc}/{loader}/profile/json"
        )),
        "quilt" => Ok(format!(
            "https://meta.quiltmc.org/v3/versions/loader/{mc}/{loader}/profile/json"
        )),
        other => Err(format!("unknown loader kind: {other}")),
    }
}

// ---------------------------------------------------------------------------
// Fetch + cache
// ---------------------------------------------------------------------------

/// Fetch and cache a loader profile for `kind` (fabric|quilt), `mc`, and `loader_version`.
///
/// The cache key is `<kind>-profile-<sanitized-mc>-<sanitized-loader>.json`, stored under
/// the app's `meta-cache/` directory.
pub async fn fetch_profile(
    app: &AppHandle,
    kind: &str,
    mc: &str,
    loader_version: &str,
) -> Result<LoaderProfile, String> {
    let url = profile_url(kind, mc, loader_version)?;
    let key = format!(
        "{}-profile-{}-{}.json",
        kind,
        sanitize(mc),
        sanitize(loader_version),
    );
    let body = meta::cached_text(app, &url, &key, TTL).await?;
    serde_json::from_str(&body).map_err(|e| format!("loader profile parse error: {e}"))
}

// ---------------------------------------------------------------------------
// Maven coordinate → relative path
// ---------------------------------------------------------------------------

/// Convert a Maven coordinate (`group:artifact:version` or
/// `group:artifact:version:classifier`) to the relative Maven repository path.
///
/// `"net.fabricmc:fabric-loader:0.16.10"` →
/// `"net/fabricmc/fabric-loader/0.16.10/fabric-loader-0.16.10.jar"`
///
/// `"a.b:c:1.0:natives"` → `"a/b/c/1.0/c-1.0-natives.jar"`
pub fn maven_coord_to_path(coord: &str) -> String {
    let parts: Vec<&str> = coord.splitn(4, ':').collect();
    // parts: [group, artifact, version, (optional classifier)]
    let group = parts.first().copied().unwrap_or("");
    let artifact = parts.get(1).copied().unwrap_or("");
    let version = parts.get(2).copied().unwrap_or("");
    let classifier = parts.get(3).copied();

    let group_path = group.replace('.', "/");

    let filename = match classifier {
        Some(cls) => format!("{artifact}-{version}-{cls}.jar"),
        None => format!("{artifact}-{version}.jar"),
    };

    format!("{group_path}/{artifact}/{version}/{filename}")
}

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

/// Make a string safe to embed in a cache filename.
fn sanitize(s: &str) -> String {
    s.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '.' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
#[path = "loader_profile_tests.rs"]
mod tests;
